"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from datetime import timedelta

# Load environment variables
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# Environment configuration
DJANGO_ENV = os.getenv('DJANGO_ENV', 'development')

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')
if not SECRET_KEY:
    raise ValueError(
        "SECRET_KEY environment variable is required. "
        "Please set it in your .env file or environment. "
        "Generate a secure key with: python -c 'from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())'"
    )

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

# HTTPS and Security Settings (Production Only)
if DJANGO_ENV == 'production':
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
else:
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    SECURE_HSTS_SECONDS = 0
    SECURE_PROXY_SSL_HEADER = None

# Cookie Settings for JWT Authentication
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Lax'


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third party apps
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "corsheaders",
    "drf_spectacular",
    # Local apps
    "users",
    "personas",
    "debates",
    "texts",
    "payments",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # Serve static files in production
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",  # CORS must be before CommonMiddleware
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv('DB_NAME', 'philosophical_debates'),
        "USER": os.getenv('DB_USER', 'postgres'),
        "PASSWORD": os.getenv('DB_PASSWORD'),
        "HOST": os.getenv('DB_HOST', 'localhost'),
        "PORT": os.getenv('DB_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Custom User Model
AUTH_USER_MODEL = "users.User"

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'users.authentication.CookieJWTAuthentication',  # Check cookie first
        'rest_framework_simplejwt.authentication.JWTAuthentication',  # Fallback to header
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',  # Will update to IsAuthenticated per view
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        # Development: Very high limits for testing
        # Production: Reasonable limits that allow active browsing while preventing abuse
        'anon': '1000/hour' if DJANGO_ENV == 'development' else '500/hour',      # ~8/min - active browsing
        'user': '2000/hour' if DJANGO_ENV == 'development' else '1500/hour',    # ~25/min - authenticated users get more
        'debate_generation': '100/hour' if DJANGO_ENV == 'development' else '10/hour',  # Resource-intensive, strict limit
    },
    'EXCEPTION_HANDLER': 'core.exceptions.custom_exception_handler',
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# drf-spectacular Configuration (API Documentation)
SPECTACULAR_SETTINGS = {
    'TITLE': 'The Infinite Debate API',
    'DESCRIPTION': (
        'API for The Infinite Debate platform - an AI-powered debate platform '
        'that brings historical thinkers to life. Generate authentic debates between '
        'philosophers, scientists, and theologians using Claude AI.\n\n'
        '**Features:**\n'
        '- Multi-persona debates with chronological turn ordering\n'
        '- Real-time debate generation with streaming updates\n'
        '- Primary text library with citation linking\n'
        '- Subscription tiers with credit-based usage\n'
        '- PDF export with citations for academic use\n\n'
        '**Authentication:**\n'
        'Most endpoints require JWT authentication. Obtain tokens via `/api/auth/login/` '
        'and include in requests as: `Authorization: Bearer <access_token>`'
    ),
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'SCHEMA_PATH_PREFIX': r'/api/',
    'SERVERS': [
        {'url': 'http://localhost:8001', 'description': 'Development server'},
        {'url': 'https://api.theinfinitedebate.com', 'description': 'Production server'},
    ],
    'TAGS': [
        {'name': 'Authentication', 'description': 'User registration, login, and profile management'},
        {'name': 'Personas', 'description': 'Historical figures available for debates'},
        {'name': 'Debates', 'description': 'Create and manage AI-generated debates'},
        {'name': 'Texts', 'description': 'Primary source library and citations'},
        {'name': 'Payments', 'description': 'Stripe subscription and payment management'},
    ],
    'CONTACT': {
        'name': 'The Infinite Debate Support',
        'email': 'support@theinfinitedebate.com',
    },
    'LICENSE': {
        'name': 'Proprietary',
    },
    'EXTERNAL_DOCS': {
        'description': 'Full Documentation',
        'url': 'https://docs.theinfinitedebate.com',
    },
    # Authentication schemes for Swagger UI
    'APPEND_COMPONENTS': {
        'securitySchemes': {
            'Bearer': {
                'type': 'http',
                'scheme': 'bearer',
                'bearerFormat': 'JWT',
            },
            'cookieAuth': {
                'type': 'apiKey',
                'in': 'cookie',
                'name': 'jwt_access_token',
            }
        }
    },
    'SECURITY': [
        {'Bearer': []},
        {'cookieAuth': []},
    ],
    # Enum generation
    'ENUM_NAME_OVERRIDES': {
        'SubscriptionTierEnum': 'users.models.User.SubscriptionTier',
        'SubscriptionStatusEnum': 'users.models.User.SubscriptionStatus',
        'DebateStatusEnum': 'debates.models.Debate.DebateStatus',
    },
}

# CORS Configuration
cors_origins = os.getenv('CORS_ALLOWED_ORIGINS', 'http://localhost:3000,http://127.0.0.1:3000,http://localhost:3001,http://127.0.0.1:3001')
CORS_ALLOWED_ORIGINS = [origin.strip() for origin in cors_origins.split(',')]

CORS_ALLOW_CREDENTIALS = True  # Required for cookies

# CSRF Trusted Origins (required for Django 4.0+ cross-origin POST requests)
csrf_origins = os.getenv('CSRF_TRUSTED_ORIGINS', 'http://localhost:3000,http://localhost:3001')
CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in csrf_origins.split(',')]

# Anthropic API Configuration
ANTHROPIC_API_KEY = os.getenv('ANTHROPIC_API_KEY', '')

# Persona files path (within backend directory)
# Persona markdown files are stored in backend/personas/fixtures/
PERSONA_FILES_PATH = Path(BASE_DIR) / 'personas' / 'fixtures'
PORTRAIT_FILES_PATH = Path(BASE_DIR).parent / 'frontend' / 'public' / 'portraits'

# Simple JWT Configuration
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
}

# Stripe Configuration
STRIPE_SECRET_KEY = os.getenv('STRIPE_SECRET_KEY', '')
STRIPE_PUBLISHABLE_KEY = os.getenv('STRIPE_PUBLISHABLE_KEY', '')
STRIPE_WEBHOOK_SECRET = os.getenv('STRIPE_WEBHOOK_SECRET', '')

# Stripe Price IDs - Starter Tier (30 credits/month, $7.99/mo or $79/yr)
STRIPE_STARTER_MONTHLY_PRICE_ID = os.getenv('STRIPE_STARTER_MONTHLY_PRICE_ID', '')
STRIPE_STARTER_YEARLY_PRICE_ID = os.getenv('STRIPE_STARTER_YEARLY_PRICE_ID', '')

# Stripe Price IDs - Pro Tier (200 credits/month, $19.99/mo or $179/yr)
STRIPE_PRO_MONTHLY_PRICE_ID = os.getenv('STRIPE_PRO_MONTHLY_PRICE_ID', '')
STRIPE_PRO_YEARLY_PRICE_ID = os.getenv('STRIPE_PRO_YEARLY_PRICE_ID', '')

# Celery Configuration
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', os.getenv('REDIS_URL', 'redis://localhost:6379/0'))
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', os.getenv('REDIS_URL', 'redis://localhost:6379/0'))
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes max for debate generation

# ============================================================================
# Sentry Error Tracking & Performance Monitoring
# ============================================================================

# Only initialize Sentry in production or when explicitly enabled
SENTRY_ENABLED = os.getenv('SENTRY_ENABLED', 'False') == 'True'
SENTRY_DSN = os.getenv('SENTRY_DSN', '')

if SENTRY_ENABLED and SENTRY_DSN:
    import sentry_sdk
    from sentry_sdk.integrations.django import DjangoIntegration
    from sentry_sdk.integrations.celery import CeleryIntegration
    from sentry_sdk.integrations.redis import RedisIntegration

    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[
            DjangoIntegration(),
            CeleryIntegration(),
            RedisIntegration(),
        ],
        
        # Set traces_sample_rate to 1.0 to capture 100% of transactions for performance monitoring.
        # We recommend adjusting this value in production.
        traces_sample_rate=float(os.getenv('SENTRY_TRACES_SAMPLE_RATE', '0.1')),
        
        # Set profiles_sample_rate to 1.0 to profile 100% of sampled transactions.
        # We recommend adjusting this value in production.
        profiles_sample_rate=float(os.getenv('SENTRY_PROFILES_SAMPLE_RATE', '0.1')),
        
        # Environment (development, staging, production)
        environment=DJANGO_ENV,
        
        # Release tracking (use git commit hash or version)
        release=os.getenv('SENTRY_RELEASE', 'philosophical-debates@dev'),
        
        # Send default PII (Personally Identifiable Information)
        send_default_pii=False,  # Set to True if you want to capture user IPs, etc.
        
        # Enable request bodies in error reports
        max_request_body_size='medium',  # 'never', 'small', 'medium', 'always'
        
        # Filter out health check noise
        before_send=lambda event, hint: (
            None if event.get('request', {}).get('url', '').endswith('/health/')
            or event.get('request', {}).get('url', '').endswith('/ready/')
            else event
        ),
        
        # Ignore specific errors (add as needed)
        ignore_errors=[
            # Django's CSRF errors are often false positives
            'django.middleware.csrf.CsrfViewMiddleware',
        ],
    )

    print(f"✅ Sentry initialized for environment: {DJANGO_ENV}")
else:
    if not SENTRY_ENABLED:
        print("⚠️  Sentry disabled (SENTRY_ENABLED=False)")
    elif not SENTRY_DSN:
        print("⚠️  Sentry DSN not configured")

# ============================================================================
# Structured Logging Configuration
# ============================================================================

# Create logs directory if it doesn't exist
LOGS_DIR = BASE_DIR / 'logs'
LOGS_DIR.mkdir(exist_ok=True)

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,

    # Formatters define how log messages are formatted
    'formatters': {
        # Verbose formatter for development - includes all details
        'verbose': {
            'format': '[{levelname}] {asctime} {name} {module}.{funcName}:{lineno} - {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },

        # Simple formatter for console output
        'simple': {
            'format': '[{levelname}] {asctime} - {message}',
            'style': '{',
            'datefmt': '%H:%M:%S',
        },

        # JSON formatter for production structured logging
        # Note: Uses standard logging, formats as JSON-like string
        'json': {
            'format': 'timestamp="{asctime}" level="{levelname}" logger="{name}" module="{module}" '
                     'function="{funcName}" line={lineno} message="{message}"',
            'style': '{',
            'datefmt': '%Y-%m-%dT%H:%M:%S',
        },
    },

    # Filters can be used to provide additional control over which log records are passed
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },

    # Handlers determine where log messages go
    'handlers': {
        # Console handler - outputs to terminal (development)
        'console': {
            'level': 'DEBUG' if DEBUG else 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple' if DEBUG else 'verbose',
        },

        # File handler for all logs (with rotation)
        'file_all': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'django_all.log',
            'maxBytes': 10 * 1024 * 1024,  # 10 MB
            'backupCount': 5,
            'formatter': 'json' if DJANGO_ENV == 'production' else 'verbose',
        },

        # File handler for errors only
        'file_error': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'django_errors.log',
            'maxBytes': 10 * 1024 * 1024,  # 10 MB
            'backupCount': 10,
            'formatter': 'json' if DJANGO_ENV == 'production' else 'verbose',
        },

        # File handler for Celery tasks
        'file_celery': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'celery.log',
            'maxBytes': 10 * 1024 * 1024,  # 10 MB
            'backupCount': 5,
            'formatter': 'json' if DJANGO_ENV == 'production' else 'verbose',
        },

        # File handler for database queries (development only)
        'file_db': {
            'level': 'DEBUG',
            'filters': ['require_debug_true'],
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'db_queries.log',
            'maxBytes': 10 * 1024 * 1024,  # 10 MB
            'backupCount': 3,
            'formatter': 'verbose',
        },

        # File handler for security events
        'file_security': {
            'level': 'WARNING',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'security.log',
            'maxBytes': 10 * 1024 * 1024,  # 10 MB
            'backupCount': 10,
            'formatter': 'json' if DJANGO_ENV == 'production' else 'verbose',
        },

        # Email handler for critical errors in production
        'mail_admins': {
            'level': 'ERROR',
            'filters': ['require_debug_false'],
            'class': 'django.utils.log.AdminEmailHandler',
            'include_html': True,
        },
    },

    # Loggers determine which handlers are used for which log sources
    'loggers': {
        # Django core logger
        'django': {
            'handlers': ['console', 'file_all', 'file_error'],
            'level': 'INFO',
            'propagate': False,
        },

        # Django request logger (HTTP requests)
        'django.request': {
            'handlers': ['console', 'file_all', 'file_error', 'mail_admins'],
            'level': 'WARNING',
            'propagate': False,
        },

        # Django database logger (SQL queries)
        'django.db.backends': {
            'handlers': ['file_db'] if DEBUG else [],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },

        # Django security logger
        'django.security': {
            'handlers': ['console', 'file_security', 'mail_admins'],
            'level': 'WARNING',
            'propagate': False,
        },

        # Celery logger
        'celery': {
            'handlers': ['console', 'file_celery', 'file_error'],
            'level': 'INFO',
            'propagate': False,
        },

        # Application-specific loggers for each app
        'debates': {
            'handlers': ['console', 'file_all', 'file_error'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },

        'personas': {
            'handlers': ['console', 'file_all', 'file_error'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },

        'texts': {
            'handlers': ['console', 'file_all', 'file_error'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },

        'users': {
            'handlers': ['console', 'file_all', 'file_error'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },

        'payments': {
            'handlers': ['console', 'file_all', 'file_error'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },

        'health': {
            'handlers': ['console', 'file_all'],
            'level': 'INFO',
            'propagate': False,
        },
    },

    # Root logger - catches everything not caught by other loggers
    'root': {
        'handlers': ['console', 'file_all', 'file_error'],
        'level': 'INFO',
    },
}

# Print logging configuration status
print(f"✅ Logging configured for environment: {DJANGO_ENV}")
print(f"   Logs directory: {LOGS_DIR}")
if DEBUG:
    print("   Log level: DEBUG (development mode)")
    print("   Database queries logged to: logs/db_queries.log")
else:
    print("   Log level: INFO (production mode)")
    print("   Format: JSON structured logging")
