# Generated by Django 5.2.7 on 2025-10-16 23:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Persona",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("title", models.CharField(blank=True, max_length=500)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("theologian", "Theologian"),
                            ("philosopher", "Philosopher"),
                            ("scientist", "Scientist"),
                        ],
                        max_length=20,
                    ),
                ),
                ("era", models.CharField(blank=True, max_length=200)),
                (
                    "birth_year",
                    models.IntegerField(
                        blank=True, help_text="For chronological ordering", null=True
                    ),
                ),
                ("death_year", models.IntegerField(blank=True, null=True)),
                ("religion_worldview", models.CharField(blank=True, max_length=200)),
                ("primary_works", models.JSONField(blank=True, default=list)),
                (
                    "core_positions",
                    models.TextField(
                        blank=True, help_text="Core philosophical positions"
                    ),
                ),
                (
                    "debate_style",
                    models.TextField(blank=True, help_text="Debate style and approach"),
                ),
                (
                    "key_concepts",
                    models.TextField(
                        blank=True, help_text="Key concepts and terminology"
                    ),
                ),
                (
                    "engagement_strategies",
                    models.TextField(
                        blank=True, help_text="How they engage with other traditions"
                    ),
                ),
                (
                    "representative_quotes",
                    models.TextField(blank=True, help_text="Representative quotes"),
                ),
                (
                    "debate_priorities",
                    models.TextField(blank=True, help_text="Debate priorities"),
                ),
                (
                    "weaknesses",
                    models.TextField(
                        blank=True, help_text="Potential weaknesses and vulnerabilities"
                    ),
                ),
                (
                    "character_notes",
                    models.TextField(
                        blank=True, help_text="Character notes for embodiment"
                    ),
                ),
                (
                    "full_markdown",
                    models.TextField(
                        blank=True, help_text="Complete markdown file content"
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        blank=True, help_text="Path to source .md file", max_length=500
                    ),
                ),
                (
                    "portrait_image",
                    models.CharField(
                        blank=True,
                        help_text="Filename of portrait image in /portraits/ (e.g., 'plato.png')",
                        max_length=200,
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["birth_year", "name"],
                "indexes": [
                    models.Index(
                        fields=["category", "birth_year"],
                        name="personas_pe_categor_cfbd1f_idx",
                    ),
                    models.Index(fields=["slug"], name="personas_pe_slug_9d7b00_idx"),
                ],
            },
        ),
    ]
