# Generated by Django 5.2.7 on 2025-10-17 01:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("personas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="persona",
            name="category",
            field=models.CharField(
                help_text="Category from directory name (e.g., theologians, philosophers, artists)",
                max_length=50,
            ),
        ),
    ]
