# Generated by Django 5.2.7 on 2025-10-17 02:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("personas", "0002_alter_persona_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="persona",
            name="is_premium",
            field=models.BooleanField(
                default=False,
                help_text="If True, only available to paid subscribers. If False, available to free tier.",
            ),
        ),
    ]
