# Generated by Django 5.2.7 on 2025-10-17 02:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("personas", "0003_add_is_premium_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="persona",
            name="is_premium",
        ),
        migrations.AddField(
            model_name="persona",
            name="required_tier",
            field=models.CharField(
                choices=[
                    ("free", "Free"),
                    ("starter", "Starter"),
                    ("pro", "Pro"),
                    ("enterprise", "Enterprise"),
                ],
                default="free",
                help_text="Minimum subscription tier required to use this persona in debates",
                max_length=20,
            ),
        ),
    ]
