# Generated by Django 5.2.7 on 2025-10-17 22:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("personas", "0004_replace_is_premium_with_required_tier"),
    ]

    operations = [
        migrations.AddField(
            model_name="persona",
            name="external_links",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="External resources: primary_works (list), wikipedia (str), stanford_encyclopedia (str), academic (list), modern (list)",
            ),
        ),
    ]
