# Generated by Django 5.2.7 on 2025-10-18 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("personas", "0005_persona_external_links"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonaRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "persona_name",
                    models.CharField(
                        help_text="Name of the requested persona", max_length=200
                    ),
                ),
                (
                    "justification",
                    models.TextField(
                        help_text="Why this persona should be added (background, relevance, contribution)"
                    ),
                ),
                (
                    "suggested_sources",
                    models.TextField(
                        blank=True,
                        help_text="Suggested sources for research (books, articles, websites)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        help_text="Current status of the request",
                        max_length=20,
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True, help_text="Internal notes from admin review"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When admin reviewed the request",
                        null=True,
                    ),
                ),
                (
                    "created_persona",
                    models.ForeignKey(
                        blank=True,
                        help_text="The persona created from this request (if completed)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="request_origin",
                        to="personas.persona",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who submitted the request",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="persona_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="personas_pe_user_id_d6d1ec_idx"
                    ),
                    models.Index(
                        fields=["status", "-created_at"],
                        name="personas_pe_status_27fecf_idx",
                    ),
                ],
            },
        ),
    ]
