# Generated by Django 5.2.7 on 2025-10-19 20:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("personas", "0006_personarequest"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="persona",
            index=models.Index(
                fields=["birth_year"], name="personas_pe_birth_y_dce734_idx"
            ),
        ),
    ]
