# Generated by Django 5.2.7 on 2025-10-18 23:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StripeEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_id",
                    models.CharField(
                        help_text="Stripe event ID", max_length=200, unique=True
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        help_text="Type of Stripe event (e.g., customer.subscription.created)",
                        max_length=100,
                    ),
                ),
                ("data", models.JSONField(help_text="Full event data from Stripe")),
                (
                    "processed",
                    models.BooleanField(
                        default=False, help_text="Whether this event has been processed"
                    ),
                ),
                (
                    "error",
                    models.TextField(
                        blank=True,
                        help_text="Any error that occurred during processing",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["event_type", "created_at"],
                        name="payments_st_event_t_af3af6_idx",
                    ),
                    models.Index(
                        fields=["processed"], name="payments_st_process_fab38c_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="StripePayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_intent_id",
                    models.CharField(
                        help_text="Stripe PaymentIntent ID", max_length=200, unique=True
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Amount in dollars", max_digits=10
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="usd", help_text="Currency code", max_length=3
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "subscription_id",
                    models.CharField(
                        blank=True,
                        help_text="Associated Stripe subscription ID",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Payment description"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional metadata"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stripe_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="payments_st_user_id_b9b18d_idx"
                    ),
                    models.Index(
                        fields=["payment_intent_id"],
                        name="payments_st_payment_06c100_idx",
                    ),
                    models.Index(
                        fields=["subscription_id"],
                        name="payments_st_subscri_e89bd3_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="StripeSubscriptionHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subscription_id",
                    models.CharField(
                        help_text="Stripe subscription ID", max_length=200
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("updated", "Updated"),
                            ("canceled", "Canceled"),
                            ("deleted", "Deleted"),
                            ("trial_will_end", "Trial Will End"),
                            ("payment_failed", "Payment Failed"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "tier",
                    models.CharField(
                        help_text="Subscription tier at time of action", max_length=20
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        help_text="Subscription status at time of action", max_length=20
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional context"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="payments_st_user_id_9c4f54_idx",
                    ),
                    models.Index(
                        fields=["subscription_id"],
                        name="payments_st_subscri_0d0b11_idx",
                    ),
                ],
            },
        ),
    ]
