# Generated by Django 5.2.7 on 2025-10-18 16:18

import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("debates", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrimaryText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                (
                    "author",
                    models.CharField(
                        help_text="Author name (could be FK to Persona in future)",
                        max_length=200,
                    ),
                ),
                ("original_language", models.CharField(blank=True, max_length=50)),
                ("publication_year", models.IntegerField(blank=True, null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("philosophy", "Philosophy"),
                            ("theology", "Theology"),
                            ("science", "Science"),
                            ("political", "Political Theory"),
                            ("ethics", "Ethics"),
                            ("economics", "Economics"),
                            ("literature", "Literature"),
                            ("psychology", "Psychology"),
                            ("other", "Other"),
                        ],
                        default="philosophy",
                        max_length=50,
                    ),
                ),
                (
                    "era",
                    models.CharField(
                        choices=[
                            ("ancient", "Ancient (Before 500 CE)"),
                            ("medieval", "Medieval (500-1500)"),
                            ("early_modern", "Early Modern (1500-1800)"),
                            ("modern", "Modern (1800-1950)"),
                            ("contemporary", "Contemporary (1950-Present)"),
                        ],
                        default="ancient",
                        max_length=50,
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        blank=True, help_text="Where we obtained this text"
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("gutenberg", "Project Gutenberg"),
                            ("mit_classics", "MIT Internet Classics"),
                            ("internet_archive", "Internet Archive"),
                            ("sacred_texts", "Sacred Texts Archive"),
                            ("perseus", "Perseus Digital Library"),
                            ("manual", "Manually Added"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "license",
                    models.CharField(
                        default="public_domain",
                        help_text="Public Domain, CC-BY, etc.",
                        max_length=100,
                    ),
                ),
                ("translator", models.CharField(blank=True, max_length=200)),
                ("translation_year", models.IntegerField(blank=True, null=True)),
                (
                    "edition_notes",
                    models.TextField(
                        blank=True, help_text="Edition info, ISBN, publisher, etc."
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Brief description of the work"
                    ),
                ),
                ("word_count", models.IntegerField(default=0)),
                (
                    "reading_difficulty",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                            ("expert", "Expert"),
                        ],
                        default="intermediate",
                        max_length=20,
                    ),
                ),
                (
                    "full_content",
                    models.TextField(
                        blank=True,
                        help_text="Complete text content (use for small texts, otherwise use sections)",
                    ),
                ),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(
                        blank=True, null=True
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata: ISBN, original_title, alternative_titles, etc.",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False, help_text="Ready for users to view"
                    ),
                ),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("ready", "Ready"),
                            ("error", "Error"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Primary Text",
                "verbose_name_plural": "Primary Texts",
                "ordering": ["author", "publication_year", "title"],
                "indexes": [
                    models.Index(
                        fields=["author", "publication_year"],
                        name="texts_prima_author_936943_idx",
                    ),
                    models.Index(
                        fields=["category", "era"],
                        name="texts_prima_categor_abc92c_idx",
                    ),
                    models.Index(fields=["slug"], name="texts_prima_slug_e3c4c1_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="TextSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("part", "Part"),
                            ("book", "Book"),
                            ("chapter", "Chapter"),
                            ("section", "Section"),
                            ("paragraph", "Paragraph"),
                            ("fragment", "Fragment"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "order_index",
                    models.IntegerField(help_text="Order within parent (0-indexed)"),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Section title (e.g., 'The Allegory of the Cave')",
                        max_length=500,
                    ),
                ),
                (
                    "reference_id",
                    models.CharField(
                        blank=True,
                        help_text="Standard reference (e.g., '514a' for Stephanus pagination in Plato)",
                        max_length=100,
                    ),
                ),
                ("content", models.TextField(help_text="The actual text content")),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(
                        blank=True, null=True
                    ),
                ),
                ("word_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent section (e.g., Book 1 is parent of Chapter 1)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="texts.textsection",
                    ),
                ),
                (
                    "text",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="texts.primarytext",
                    ),
                ),
            ],
            options={
                "ordering": ["text", "order_index"],
            },
        ),
        migrations.CreateModel(
            name="TextCitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "citation_text",
                    models.TextField(
                        help_text="The actual citation text from the debate (e.g., 'As I wrote in the Republic...')"
                    ),
                ),
                (
                    "extracted_quote",
                    models.TextField(
                        blank=True, help_text="Direct quote if citation includes one"
                    ),
                ),
                (
                    "match_confidence",
                    models.FloatField(
                        default=0.5,
                        help_text="0.0-1.0 confidence that this citation is correctly linked",
                    ),
                ),
                (
                    "match_method",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("regex", "Regex Pattern"),
                            ("nlp", "NLP Extraction"),
                            ("llm", "LLM Extraction"),
                        ],
                        default="regex",
                        max_length=50,
                    ),
                ),
                (
                    "verified",
                    models.BooleanField(
                        default=False,
                        help_text="Has a human verified this citation is correct?",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "debate_message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="text_citations",
                        to="debates.debatemessage",
                    ),
                ),
                (
                    "text",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="citations",
                        to="texts.primarytext",
                    ),
                ),
                (
                    "text_section",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific section cited (if identifiable)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="citations",
                        to="texts.textsection",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="textsection",
            index=models.Index(
                fields=["text", "section_type", "order_index"],
                name="texts_texts_text_id_d30cf0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="textsection",
            index=models.Index(
                fields=["reference_id"], name="texts_texts_referen_d80eaf_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="textsection",
            unique_together={("text", "parent", "order_index")},
        ),
        migrations.AddIndex(
            model_name="textcitation",
            index=models.Index(
                fields=["debate_message"], name="texts_textc_debate__860270_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="textcitation",
            index=models.Index(fields=["text"], name="texts_textc_text_id_988c37_idx"),
        ),
        migrations.AddIndex(
            model_name="textcitation",
            index=models.Index(
                fields=["verified", "match_confidence"],
                name="texts_textc_verifie_e1126b_idx",
            ),
        ),
    ]
