# Generated by Django 5.2.7 on 2025-10-18 17:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("texts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="textsection",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="Section title (e.g., 'The Allegory of the Cave')",
                max_length=500,
                null=True,
            ),
        ),
    ]
