# Generated by Django 5.2.7 on 2025-10-16 23:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("personas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DebateMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "round_number",
                    models.IntegerField(help_text="Which round of the debate"),
                ),
                ("content", models.TextField(help_text="The persona's statement")),
                (
                    "tokens_used",
                    models.IntegerField(
                        default=0, help_text="API tokens used for this message"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["debate", "round_number", "persona__birth_year"],
            },
        ),
        migrations.CreateModel(
            name="Debate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                (
                    "topic",
                    models.TextField(help_text="The question or topic being debated"),
                ),
                ("slug", models.SlugField(max_length=200, unique=True)),
                (
                    "depth_level",
                    models.CharField(
                        choices=[
                            ("introductory", "Introductory"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        default="intermediate",
                        max_length=20,
                    ),
                ),
                (
                    "max_rounds",
                    models.IntegerField(
                        default=10, help_text="Maximum number of debate rounds"
                    ),
                ),
                (
                    "credits_used",
                    models.IntegerField(
                        default=0, help_text="Credits consumed by this debate"
                    ),
                ),
                (
                    "transcript",
                    models.TextField(
                        blank=True, help_text="Full debate transcript in markdown"
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True, help_text="AI-generated summary of the debate"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("generating", "Generating"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("rounds_completed", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "participants",
                    models.ManyToManyField(
                        related_name="debates", to="personas.persona"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
