# Generated by Django 5.2.7 on 2025-10-16 23:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("debates", "0001_initial"),
        ("personas", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="debate",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="debates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="debatemessage",
            name="debate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="debates.debate",
            ),
        ),
        migrations.AddField(
            model_name="debatemessage",
            name="persona",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="personas.persona"
            ),
        ),
        migrations.AddIndex(
            model_name="debate",
            index=models.Index(
                fields=["user", "-created_at"], name="debates_deb_user_id_69943f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="debate",
            index=models.Index(fields=["status"], name="debates_deb_status_c554b4_idx"),
        ),
        migrations.AddIndex(
            model_name="debatemessage",
            index=models.Index(
                fields=["debate", "round_number"], name="debates_deb_debate__193fc4_idx"
            ),
        ),
    ]
