# Generated by Django 5.2.7 on 2025-10-19 20:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("debates", "0003_add_topic_validators"),
        ("personas", "0007_persona_personas_pe_birth_y_dce734_idx"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="debatemessage",
            index=models.Index(
                fields=["debate", "round_number", "persona"],
                name="debates_deb_debate__0ddaf8_idx",
            ),
        ),
    ]
