# Generated by Django 5.2.7 on 2025-10-16 23:58

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "subscription_tier",
                    models.CharField(
                        choices=[
                            ("trial", "Trial"),
                            ("starter", "Starter"),
                            ("pro", "Pro"),
                            ("enterprise", "Enterprise"),
                        ],
                        default="trial",
                        help_text="User's current subscription tier",
                        max_length=20,
                    ),
                ),
                (
                    "subscription_status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                            ("past_due", "Past Due"),
                        ],
                        default="active",
                        help_text="Status of the subscription",
                        max_length=20,
                    ),
                ),
                (
                    "credits_remaining",
                    models.IntegerField(
                        default=15,
                        help_text="Credits available this billing period (15 for trial)",
                    ),
                ),
                (
                    "credits_reset_date",
                    models.DateField(
                        blank=True,
                        help_text="Date when credits will reset (monthly)",
                        null=True,
                    ),
                ),
                (
                    "trial_start_date",
                    models.DateTimeField(
                        blank=True, help_text="When the trial period started", null=True
                    ),
                ),
                (
                    "trial_end_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the trial period ends (7 days from start)",
                        null=True,
                    ),
                ),
                (
                    "stripe_customer_id",
                    models.CharField(
                        blank=True, help_text="Stripe customer ID", max_length=200
                    ),
                ),
                (
                    "stripe_subscription_id",
                    models.CharField(
                        blank=True, help_text="Stripe subscription ID", max_length=200
                    ),
                ),
                (
                    "email_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the user's email has been verified",
                    ),
                ),
                (
                    "email_verification_token",
                    models.CharField(
                        blank=True,
                        help_text="Token for email verification",
                        max_length=200,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["subscription_tier", "subscription_status"],
                        name="users_user_subscri_163efa_idx",
                    ),
                    models.Index(
                        fields=["email_verified"], name="users_user_email_v_d8053a_idx"
                    ),
                    models.Index(
                        fields=["stripe_customer_id"],
                        name="users_user_stripe__26a84b_idx",
                    ),
                ],
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
