# Generated by Django 5.2.7 on 2025-10-25 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stripe_payment_method_id',
            field=models.CharField(blank=True, help_text='Stripe payment method ID (credit card on file)', max_length=200),
        ),
    ]
